baseURL = 'https://baust.me/'
languageCode = 'en-gb'
title = 'Andrew Craig'
theme = 'hugo-bearcub'

[author]
  name = 'Andrew'
  email = 'andrew@baust.me'

[params]
  description = "A minimalist website built with Hugo amd Bear Cub."

[[menu.main]]
    name = "Posts"
    url = "/blog/"
    weight = 1    

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2   


[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 3
  
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
